In [2]:
import numpy as np

In [14]:
a = np.array([1,4,2],dtype="int16")

In [3]:
a

array([1, 4, 2])

In [4]:
print(a)

[1 4 2]


In [7]:
b = np.array([[[1,432,1313,232],[123213,3232,3213,3213],[323,4324,4324,4234]]])
print(b)

[[[     1    432   1313    232]
  [123213   3232   3213   3213]
  [   323   4324   4324   4234]]]


In [7]:
#get dimension of array
a.ndim

1

In [8]:
b.ndim

3

In [9]:
b.shape

(1, 3, 4)

In [10]:
a.shape

(3,)

In [15]:
# get type in bits
a.dtype

dtype('int16')

In [16]:
# get size in bytes
a.itemsize

2

In [17]:
# get total size
a.nbytes

6

In [3]:
c = np.array([[1,2,42,2,4,23,5],[4,232,43,534,53,23,32]])
c.shape

(2, 7)

In [19]:
# get a specific position value from c
c[1][5]

23

In [20]:
c[1,5]

23

In [21]:
c[1,-2]

23

In [22]:
# get a specific row
c[1]

array([  4, 232,  43, 534,  53,  23,  32])

In [23]:
c[1,:]

array([  4, 232,  43, 534,  53,  23,  32])

In [24]:
# get a specific column
c[:,2]

array([42, 43])

In [25]:
print(c)

[[  1   2  42   2   4  23   5]
 [  4 232  43 534  53  23  32]]


In [4]:
# getting a little more fancy [startindex:endindex:stepsize]
c[0,1:6:2]

array([ 2,  2, 23])

In [5]:
c[1, 1:4] = 22

In [6]:
c

array([[ 1,  2, 42,  2,  4, 23,  5],
       [ 4, 22, 22, 22, 53, 23, 32]])

In [8]:
b.shape

(1, 3, 4)

In [9]:
b.ndim

3

In [13]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
# any other numbers
np.full((2,3,2),255)

array([[[255, 255],
        [255, 255],
        [255, 255]],

       [[255, 255],
        [255, 255],
        [255, 255]]])

In [16]:
# take same size of existing array
np.full_like(b,22)

array([[[22, 22, 22, 22],
        [22, 22, 22, 22],
        [22, 22, 22, 22]]])

In [17]:
np.full(b.shape,255)

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]])

In [19]:
# create random array
np.random.rand(2,3)

array([[0.55048239, 0.37104862, 0.54484312],
       [0.45169084, 0.89789524, 0.48692069]])

In [21]:
# create random integers
np.random.randint(-33,3,size=(3,2))

array([[ -9, -17],
       [ -1,  -7],
       [-13,  -4]])

In [22]:
# create identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
a = np.ones((5,5),dtype='int32')
z = np.zeros((3,3),dtype='int32')
z[1,1] = 9
a[1:4,1:4] = z
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [38]:
a.ndim

2

##Be careful when copying arrays!!

#Comment

test comment

In [44]:
a = np.array([1,2,3])
b = a.copy()   # correct way to copy, wrong way b = a
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics

In [45]:
a_sample = [1,2,3,4]

In [46]:
a_sample * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [48]:
a = np.array([1,2,3,4])

In [49]:
a * 3

array([ 3,  6,  9, 12])

In [50]:
b_sample = [2,2,2,2]

In [51]:
a_sample + b_sample

[1, 2, 3, 4, 2, 2, 2, 2]

In [52]:
b = np.array([2,2,2,2])

In [53]:
a + b

array([3, 4, 5, 6])

In [54]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [55]:
# get sin of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

####### Linear Alegebra

##### Linear Algebra

In [56]:
a = np.ones((2,3))

In [57]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
b = np.full((3,2),2)

In [59]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [60]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

###### Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])

In [62]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.min(stats)

1

In [64]:
np.max(stats)

6

In [65]:
np.sum(stats)

21

In [73]:
stats.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [76]:
np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [77]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

In [78]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [79]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [84]:
a.reshape((1,30))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [88]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [91]:
b = a[0,3:5]

In [92]:
b

array([4, 5])

In [99]:
c = a[4:6,3:5]

In [100]:
c

array([[24, 25],
       [29, 30]])

In [101]:
d = np.vstack([b,c])

In [102]:
d

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [103]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])